### PR TITLE
I added a .py file but can't delete an old folder!

### PR DESCRIPTION
**Pull request by GregoryFenn**
I added a solution source code to challenge 2 to matasano-challenges/python, but my branch (and hence this pull request) has that old Gregs_solutions folder 

I can't delete it now :/

### CODE REVIEW

**Comment by samscott89** [comment]
You can use `git rm <file>` to delete any files from your git repository.

This will delete them from your computer as well. `git rm --cached <file>` deletes it from git but leaves it in your working directory.

**Comment by RPL226** [comment]
I was looking at your code and generally I think it looks to do the job nicely.  However, I'd like to suggest a couple of adjustments as there were some things I wasn't sure about.

Firstly, although it might be in the file you're trying to remove, in challenge-2_Gregsolution.py there is a function called xor_of_two_hexstrings.  In this function you decode the inputs hexs1 and hexs2 and save them into variables rhs and lhs, personally I'd expect you to call things rhs and lhs only if you were going to append them together.  I'd probably go with inputs of hex1string and hex2string then you could decode them into hex1int and hex2int which might be a bit clearer.  I have a similar complaint about the functions xor_of_n_hexstrings and xor_of_n_hexstrings__alternate.

Secondly, xor_of_n_hexstrings and xor_of_n_hexstrings__alternate both return ints if the inputs are empty.  I feel like that is not a good idea, would empty string not be more appropriate?

Finally, your decode function is called make_hexstring_a_decimal.  My opinion is that that is not an accurate name for the function.  Computers don't do decimal as all signals are in base 2 and not base 10.  I'd be happier if the function was called make_hexstring_an_integer or decode_hex_string.  If this change is made then I guess this might mean it would make sense to rename int_number_to_hex_string to something which fit with the first command, say make_integer_a_hexstring?

Also, thanks for using assert type(var) = x.  I didn't know it existed and I'm glad to now know that it does, is it generally good practice to use it at the start of every function in python and does it also allow checking of lists say assert type(var) = [int]?

**Comment by GregoryFenn** [comment]
Does this go to Rob and Sam?




Sam — The folder Gregs_solutions doesn’t exist in my local computer anymore:

“
Gregorys-MacBook-Pro:matasano-challenges PBVA007$ git rm Gregs_solutions
fatal: Not a git repository (or any of the parent directories): .git
Gregorys-MacBook-Pro:matasano-challenges PBVA007$ git rm --cached Gregs_solutions
fatal: Not a git repository (or any of the parent directories): .git
“

Rob — 
- The lhs and rhs side terms only refer to the functional code to easy reference to them so that readers know which one we’re talking about, hex1str and hex1int does the job too though. Most of the semantic work in a good python script is done with informative function and variable names, the stuff inside a function shouldn’t ever be too complex that it requires much interpretative help! But I’ll edit it to show the changes from str to int types more explicitly, I agree that that it always good practice.

[There is a style of python called hungarian notation, where the expected types of variables, or function outputs, is encoded in the namespace. But many python programmers frown upon it because it can give a false sense of security: a function that is named in such a way that it looks like it returns an int might really return an str. I suppose you could avoid this by finishing all functions with “assert type(f) == _type” — maybe we should discuss using hungarian notation this week?]  

Ok I’ll change the string manipulation functions to only ever return string types, “” when there is no input. 


As for your last concern about the name “make_hexstring_a_decimal”. That’s debatable. Yes computers work on bits, but the pythonic language is meant to work in a metaphysical space higher-level objects such as int (base-ten by default), str, list, set, dict, module, type, function, range, tuple, etc etc. Programmers that want to work in metaphysical space of 1s and 0s would need to work lower down e.g. Assembly code! The point of python is that it’s the logic behind the algorithm that is interesting, not the mechanics of the computer! 

I do not know if their is a direct way to test the types of iterator objects: if I run type on
(2, 3, 42)
[3, 42234, 123]
[“hello”, “world”]
{“Greg”: “Awesome”, “Rob”:”Cool”, “Sam”:”Funky”}
[1, “1”, “one”]
we would return tuple, list, list, dict, list. There is no type difference between [1, 1], [1, “1”] or [“1”, “1”]. 
That’s why when I test hex strings, I have to first check the type is str, and then separately iterate over items in the string (a string is a utterable object over it’s characters) to check that they are all hexadecimal digits. 

There may well be a more efficient way or doing it. But intuitively any such test would have to iterate over the items in a list to check what type they are, so I don’t see how this could be shortcutted anymore?

~Many thanks. 



pbva007
Gregory Joseph Fenn
pbva007@live.rhul.ac.uk
gregory.fenn.2014@rhul.ac.uk
gregory.fenn.2014@live.rhul.ac.uk

**Comment by RPL226** [comment]
Greg, it looks like the git rm has worked?  The commit is only showing one file.

Thanks for making the change to xor_of_two_hexstrings.  I haven't any idea what hungarian notation is in this setting so it might be worth discussing either on Wednesday or privately.

Thanks for changing the string functions.

I would be happier if the function names didn't make references to decimal as I don't believe that python stores data in base 10.  It may be the default for python to print numbers in base 10, probably to make it easier for humans to understand the output but that is a decision that's been made regarding the print function and I'd be amazed if it was actually the case that python stored data in BCD or some other method for storing in base 10.  I expect we will need to ask other people to contribute their opinions on this one.

Finally, I managed to answer my own question.  In my pull request there are a few examples of it in the wild but this is how I've asserted lists of integers.

assert type(var) == list
for x in var:
    assert type(x) == int

**Pull request closed without merging**
